#!/bin/bash
#for
set -v
#set -x
for((i=1;i<=9;i++))
do
	for((j=1;j<=i;j++))
	do
	echo -n "$j*$i = $(($i*$j)) "
	done
	echo
done	
#while
i=1;
while ((i<=9))
do
	j=1;
	while ((j<= i))
	do
		echo -n "$j*$i=$((i*j)) "
		j=$((j+1))
	done
	echo ""
	i=$((i+1))
done
#until
i=1
until ((i >9))
do
	j=1;
	until ((j > i))
	do
	echo -n "$j*$i=$((i*j)) "
	j=$((j+1))
	done
	echo ""
	i=$((i+1))
done
