#!/bin/bash
# testing the C-style for loop
set -x
#for (( i=1; i<= 10; i++ ))
for (( a=1, b=10; a <= 10; a++, b-- ))
do
#	echo "The next number is $i"
	echo "$a - $b"

#var1=10

#while [ $var1 -gt 0 ]
#do
#	echo $var1
#	var1=$[ $var1 - 1 ]
done

